#!/usr/bin/env python3
"""Authored alpha roster. Integer units/ticks; run to emit canonical content/roster.json."""
import json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
if (ROOT/'content/roster.json').exists() and '--replace-canonical' not in sys.argv:
    raise SystemExit('Canonical roster already exists. Edit it directly; --replace-canonical resets all balance tuning.')
Q=1024
KINDS=['Melee','Bolt','Lunge','Field','Evade','Beam','Nova','Trap','Ward','Blink','Turret']
PASSIVES=['Cinder','Anchor','Focus','Conduit','Venom','Bulwark','Frost','Backstab','Mirror','Rainborn','Trapper','Renewal','Ambush','Ricochet','Wounder','Sanctuary','Tailwind','Berserk','Cadence','Nullify','Architect','Returner','Reservoir','Leech','Resonance','Forge','Skirmish','Tether','Overheat','Retaliate','Recycle','Harvest','Cover','Hunter','Corrode','Purify','Rhythm','Web','Magazine','Resolve']
def M(name,kind='Melee',**kw):
    base=dict(name=name,kind=kind,startup=6,active=3,recovery=9,cooldown=27,cost=90,damage=16,range=1800,radius=800,speed=0,impulse=0,burn=0,haste=0,pierces_evasion=0,min_range=0,lifetime=0,period=15,shots=1,spread=0,slow=0,root=0,silence=0,poison=0,wound=0,mark=0,shield=0,heal=0,guard=0,cleanse=0,drain=0,bonus_mark=0,execute=0,health_cost=0,bounces=0,returning=0,pierce=0)
    templates={
      'Bolt':dict(startup=10,active=1,recovery=11,cooldown=36,cost=130,damage=18,range=11500,radius=200,speed=430),
      'Lunge':dict(startup=8,active=7,recovery=14,cooldown=66,cost=190,damage=21,range=1400,radius=650,speed=380),
      'Field':dict(startup=15,active=1,recovery=14,cooldown=105,cost=210,damage=4,range=4800,radius=1800,lifetime=150,period=24),
      'Beam':dict(startup=18,active=1,recovery=17,cooldown=66,cost=190,damage=25,range=11000,radius=280),
      'Nova':dict(startup=14,active=2,recovery=15,cooldown=75,cost=170,damage=22,range=0,radius=2800),
      'Trap':dict(startup=10,active=1,recovery=10,cooldown=81,cost=150,damage=18,range=5000,radius=1100,lifetime=270,root=15),
      'Ward':dict(startup=3,active=1,recovery=9,cooldown=120,cost=160,damage=0,range=0,radius=0,shield=22,guard=24),
      'Blink':dict(startup=8,active=1,recovery=13,cooldown=135,cost=230,damage=0,range=3500,radius=0),
      'Turret':dict(startup=18,active=1,recovery=15,cooldown=180,cost=260,damage=7,range=4000,radius=580,lifetime=240,period=27,speed=310)
    }
    base.update(templates.get(kind,{}));base.update(kw);return base
rows=[]
def S(name,role,passive,identity,loop,counter,learn,moves,hp=120,speed=156,radius=460,regen=6,mass=100,reach=4300,axes=(3,3,3,3,3,3,3,3)):
    rows.append(dict(id=len(rows),name=name,role=role,passive=passive,identity=identity,loop=loop,counterplay=counter,learning_test=learn,hp=hp,speed=speed,radius=radius,regen=regen,mass=mass,preferred_range=reach,axes=list(axes),moves=moves))
S('Cinderfox','burn detonator','Cinder','A glassy fox that cashes out burn windows.','Tag with Wickshot, approach under flare, cash out burn with Kindlebite.','Dodge the tag and re-engage after the burn expires; the fox has no heal.','Withhold the finisher until burn is active; stop chasing through enemy terrain.',[
 M('Kindlebite',damage=18,burn=30),M('Wickshot','Bolt',damage=13,burn=90),M('Flare Step','Lunge',damage=13,haste=45),M('Ash Circle','Field',damage=3,burn=45,lifetime=120)],hp=108,speed=170,reach=3300,axes=(3,4,4,1,3,1,1,4))
S('Brambleback','stationary bastion','Anchor','A rooted hedgehog that becomes expensive to evict.','Set a garden, stop moving to grow a shield, use roots to hold the bloom.','Force relocation with remote damage; do not fight inside the garden.','Choose when immobility is worth its defenses.',[
 M('Briar Club',damage=19,slow=30),M('Rootfurrow','Bolt',damage=12,speed=290,root=18),M('Bramble Garden','Field',damage=4,heal=2,range=1200,radius=2300),M('Barkskin','Ward',shield=29,guard=36)],hp=148,speed=124,mass=145,reach=2200,axes=(2,2,1,4,5,3,5,2))
S('Glasswing','minimum-range artillery','Focus','A brittle dragonfly whose cannon rewards stillness.','Establish distance, charge focus by standing, fire through narrow lanes.','Cross the minimum range during a long windup; force repeated turns and moves.','Find safe stationary firing windows without abandoning the objective.',[
 M('Needle Ray','Beam',damage=29,range=15500,min_range=3500,startup=24,radius=170),M('Glass Shards','Bolt',damage=8,shots=3,spread=190),M('Wing Slip','Blink',range=2800),M('Repulsion','Nova',damage=12,impulse=750,radius=2600)],hp=96,speed=151,reach=8500,axes=(5,5,2,2,1,1,1,5))
S('Voltjack','mark-and-discharge diver','Conduit','A conductive jackal that turns wet tags into dive windows.','Mark with Spark Pin, cross the gap, discharge marks at close range.','Spread the engage and deny the mark; dry conditions reduce its spike.','Choose between ranged probing and a committed marked-target dive.',[
 M('Spark Pin','Bolt',damage=12,mark=120),M('Arc Fang','Lunge',damage=19,bonus_mark=12),M('Discharge','Nova',damage=17,bonus_mark=15,radius=2200),M('Static Screen','Ward',shield=18,haste=45)],hp=115,speed=169,reach=2600,axes=(3,5,4,2,1,1,2,4))
S('Miretoad','stacking attrition','Venom','A squat toad whose poison needs repeated access.','Apply venom at several ranges, maintain stacks, heal while the poison works.','Break contact long enough for stacks to expire, then burst the slow body.','Preserve stacks without trading all of its health for one extra hit.',[
 M('Venom Tongue',range=2500,radius=850,damage=10,poison=150),M('Spitball','Bolt',damage=10,poison=150,speed=320),M('Mire Pool','Field',damage=2,poison=90,slow=30),M('Digest','Ward',shield=0,guard=0,heal=15,cooldown=180,startup=18)],hp=132,speed=135,regen=7,reach=3700,axes=(3,2,1,3,5,4,2,3))
S('Basaltusk','wall-slam juggernaut','Bulwark','A heavy boar that wants the opponent between tusks and stone.','Approach facing threats, pull into range, drive the opponent into terrain.','Flank the frontal armor; leave a lateral escape before the ram.','Line up wall collisions instead of charging directly at every target.',[
 M('Stone Tusk',damage=20,impulse=300),M('Fault Ram','Lunge',damage=23,impulse=1000,speed=440,startup=13),M('Quarry Hook','Beam',damage=12,impulse=-850,range=6800,startup=18),M('Bedrock','Ward',shield=28,guard=36,cleanse=1)],hp=154,speed=125,mass=170,reach=2300,axes=(2,5,2,4,1,1,5,4))
S('Rimehare','spacing and chill','Frost','A fast hare that converts repeated slows into brief roots.','Clip approach paths, build chill through repeat tags, escape before commitment.','Bait the escape then attack from another angle; its direct burst is low.','Lead lateral movement and conserve dodge for the engage.',[
 M('Icicle','Bolt',damage=13,slow=45,speed=500),M('Snowshoe','Lunge',damage=9,slow=30,speed=430,active=5,recovery=8),M('Frost Lace','Field',damage=2,slow=45,lifetime=150),M('Whiteout','Nova',damage=14,slow=60,impulse=300)],hp=102,speed=190,reach=5300,axes=(4,2,5,4,3,1,1,4))
S('Gloamcat','positional assassin','Backstab','A shadow cat paid for reaching the unguarded side.','Blink across a firing angle, mark the prey, punish from behind.','Track the blink endpoint and rotate your facing; punish missed lunges.','Reason about opponent orientation rather than only distance.',[
 M('Backfang',damage=20,execute=10),M('Dusk Needle','Bolt',damage=10,mark=90,range=7600),M('Night Pounce','Lunge',damage=22,bonus_mark=10,speed=440),M('Crossfade','Blink',range=3800,haste=30)],hp=100,speed=180,reach=1600,axes=(2,5,5,1,1,1,1,5))
S('Ironmoth','projectile counterfighter','Mirror','A metal moth that reflects a projectile during guard.','Threaten reflective guard to buy space; punish the opponent for waiting.','Use beams, zones or a melee approach, and bait the guard first.','Time a guard to projectile arrival rather than cast start.',[
 M('Steel Dust','Bolt',damage=9,shots=3,spread=220,range=7000),M('Mirror Carapace','Ward',shield=14,guard=18,cooldown=90),M('Shear Wing','Melee',damage=21,wound=60),M('Magnet Wake','Field',damage=3,slow=30)],hp=125,speed=146,mass=120,reach=3500,axes=(3,2,2,2,3,1,5,5))
S('Tidecoil','pull-and-pool control','Rainborn','An eel that is faster and more sustainable on wet ground.','Pull enemies into a pool and hold a favorable close-mid range.','Dodge the pull, leave the pool, and capitalize on dry-weather weakness.','Compensate for wind and choose pull angles that do not help the enemy.',[
 M('Undertow','Beam',damage=15,impulse=-700,range=8000,slow=30),M('Tidal Bite',damage=19),M('Rain Basin','Field',damage=3,heal=2,slow=20),M('Surge','Lunge',damage=12,haste=60)],hp=124,speed=154,reach=3100,axes=(3,3,3,4,4,3,2,4))
S('Quillrat','visible trap planner','Trapper','A small rodent paid for convincing enemies to take a route.','Place visible traps near likely paths; herd with shots and knockback.','Clear or route around trap circles and attack before the field is prepared.','Predict future positions rather than planting directly under the current enemy.',[
 M('Barb Shot','Bolt',damage=13,speed=390),M('Caltrop','Trap',damage=23,root=21),M('Needle Fence','Field',damage=4,slow=30,radius=1400),M('Panic Quills','Nova',damage=13,impulse=550)],hp=108,speed=167,reach=5000,axes=(4,2,3,4,5,1,1,5))
S('Sunstag','cleanse-and-tempo skirmisher','Renewal','A stag that turns a defensive cleanse into tempo.','Absorb a debuff, cleanse it, use the haste window to control center.','Delay crowd control until cleanse is gone; contest its long-cooldown recovery.','Distinguish valuable cleanse timing from using every spell on cooldown.',[
 M('Sun Antler',damage=18,mark=75),M('Daybreak','Beam',damage=19,bonus_mark=9,range=8500),M('Golden Bound','Lunge',damage=13,haste=45),M('Renew','Ward',shield=10,heal=12,cleanse=1,cooldown=165)],hp=123,speed=163,reach=3000,axes=(3,3,4,1,1,4,3,3))
S('Gravemole','delayed ambusher','Ambush','A burrowing mole that empowers its next hit after displacement.','Show a delayed eruption, blink to a new line, land the empowered attack.','Move out of the eruption and hold defense for the post-blink hit.','Coordinate delayed ground damage with its own arrival.',[
 M('Grave Claw',damage=19),M('Burrow','Blink',range=4200,startup=12),M('Upheaval','Trap',damage=25,root=12,startup=16,radius=1550),M('Tunnel Rush','Lunge',damage=16,impulse=350)],hp=117,speed=153,reach=2200,axes=(2,5,4,3,3,1,2,5))
S('Prismray','ricochet geometry','Ricochet','A ray that makes walls into indirect firing lanes.','Bank shots around rocks, then exploit forced sidesteps with a narrow beam.','Fight in open space or close the gap while the bank shot travels.','Discover wall angles and distinguish return paths from initial aim.',[
 M('Prism Dart','Bolt',damage=15,bounces=1,speed=490,range=15000),M('Split Spectrum','Bolt',damage=9,shots=3,spread=260,bounces=1),M('Refraction','Beam',damage=24,startup=20,radius=180),M('Prism Fold','Blink',range=2600,cooldown=150)],hp=104,speed=151,reach=6500,axes=(5,4,2,1,2,1,1,5))
S('Thornmantis','wound pursuit duelist','Wounder','A mantis that invests in a wound before its real trade.','Open a wound, stick briefly, cash out a high-damage cut.','Kite the short blades and wait out the wound before using a heal.','Sequence setup and payoff while preserving an exit.',[
 M('Open Seam',damage=12,wound=120),M('Harvest Cut',damage=23,startup=10,cooldown=48),M('Thorn Leap','Lunge',damage=17,wound=60),M('Razor Guard','Ward',shield=17,guard=18,haste=30)],hp=119,speed=173,reach=1700,axes=(1,4,4,1,1,2,2,4))
S('Mosswarden','territory sustain','Sanctuary','A moss-covered giant that heals only while owning a patch.','Seed shelter on the objective, defend it, replenish slowly between trades.','Displace it out of the shelter or apply wounds before committing damage.','Weigh staying inside a heal zone against avoiding incoming area attacks.',[
 M('Moss Fist',damage=20,slow=24),M('Seed Bomb','Bolt',damage=15,speed=300),M('Shelter Grove','Field',damage=2,heal=3,radius=2400,range=2600),M('Living Wall','Ward',shield=32,guard=24)],hp=145,speed=127,mass=145,reach=2100,axes=(2,2,1,2,5,5,4,2))
S('Galecrest','wind mobility','Tailwind','A crestbird that turns wind into unusually fast rotations.','Sweep the opponent off a line, reposition, send a fan into their exit.','Use terrain to shorten its strafe path and exploit its thin health pool.','Learn different projectile leads and approach paths in each weather preset.',[
 M('Feather Fan','Bolt',damage=8,shots=3,spread=210,speed=480),M('Gust Lance','Beam',damage=15,impulse=600,range=9000),M('Jetstream','Lunge',damage=13,speed=500,active=6),M('Updraft','Nova',damage=14,impulse=450,haste=45)],hp=101,speed=181,reach=4800,axes=(4,3,5,3,1,1,1,4))
S('Ashram','health-spending berserker','Berserk','A ram that pays real health to create lethal windows.','Spend health to enter, exploit missing-health damage, extract through a small heal.','Deny the last hit, disengage through its haste, punish reckless self-costs.','Estimate whether the all-in wins before sacrificing its safety buffer.',[
 M('Blood Horn',damage=22,health_cost=4,cost=60),M('Cinder Charge','Lunge',damage=25,health_cost=6,impulse=400),M('Fury','Ward',shield=0,guard=0,haste=75,health_cost=5,cooldown=120),M('Last Ember','Nova',damage=24,execute=14,heal=7,startup=18)],hp=137,speed=158,reach=1800,axes=(1,5,3,1,1,2,1,4))
S('Clockfin','alternating-combo engine','Cadence','A clockwork fish paid for changing spell slots.','Alternate cheap tools with expensive payoffs to recover energy.','Force a repeated defensive spell or interrupt the slow payoff.','Learn a flexible sequence instead of a fixed highest-DPS button.',[
 M('Tick','Bolt',damage=12,cooldown=24,cost=100),M('Tock','Beam',damage=22,cooldown=57,cost=200),M('Second Hand','Lunge',damage=14,cooldown=51),M('Windup Key','Ward',shield=18,guard=12,haste=45)],hp=117,speed=155,regen=4,reach=4000,axes=(3,3,3,1,1,2,2,5))
S('Nullurchin','anti-shield disruptor','Nullify','An urchin that punishes protective-resource dependence.','Strip shields with safe pokes, silence a recovery spell, take ground.','Offer raw health instead of shields and pressure its poor mobility.','Identify when disruption matters more than the largest damage number.',[
 M('Null Spine','Bolt',damage=15,drain=60),M('Mute Line','Beam',damage=17,silence=24,range=8500),M('Deadwater','Field',damage=3,wound=60),M('Void Shell','Ward',shield=25,guard=24)],hp=134,speed=130,mass=135,reach=4300,axes=(4,3,1,4,3,1,4,4))
S('Waxwyrm','destructible turret engineer','Architect','A wax wyrm whose strength has a separate health bar.','Build a turret with crossfire, defend it with slows and body positioning.','Aim at the turret to destroy it before fighting in its lane.','Place summons where their line of sight and survival both matter.',[
 M('Wax Glob','Bolt',damage=13,slow=24,speed=330),M('Candle Sentry','Turret',damage=8),M('Hot Seal','Field',damage=4,range=3800),M('Wax Jacket','Ward',shield=26,guard=18)],hp=118,speed=137,reach=4300,axes=(4,2,1,3,5,1,3,5))
S('Ribbonape','return-path fighter','Returner','A ribbon-tailed ape that hits along outbound and return paths.','Throw a ribbon, change position, make the returning arc cross the enemy.','Step off the return line rather than blindly dodging the first pass.','Use locomotion to steer an existing projectile.',[
 M('Ribbon Throw','Bolt',damage=12,returning=1,speed=370,range=7000,lifetime=48),M('Tail Snap',damage=20,impulse=-250),M('Acrobat','Lunge',damage=12,speed=420,active=5,haste=30),M('Silk Whorl','Nova',damage=17,slow=30)],hp=117,speed=172,reach=3300,axes=(3,3,4,2,2,1,2,5))
S('Saltcrab','resource fortress','Reservoir','A crab that replenishes stamina during guard.','Block while refilling, then spend a full bar to bully a short-range fight.','Wait out the shell and attack while it is spending; displace it off center.','Use defensive downtime as a resource reset rather than permanent turtling.',[
 M('Salt Pinch',damage=21,cost=170),M('Brine Cannon','Bolt',damage=22,cost=230,speed=350),M('Closed Shell','Ward',shield=26,guard=42,cooldown=132),M('Scuttle','Lunge',damage=12,speed=330,active=6)],hp=150,speed=123,regen=3,mass=165,reach=2400,axes=(2,3,1,2,1,2,5,3))
S('Nectarbat','access-dependent lifesteal','Leech','A bat that survives by landing risky direct hits.','Take repeated short trades, heal on contact, exit before crowd control lands.','Apply wounds or deny contact; its sustain vanishes while kited.','Select safe access windows instead of interpreting lifesteal as permission to face-tank.',[
 M('Siphon Fang',damage=19),M('Nectar Needle','Bolt',damage=13,range=8000),M('Swoop','Lunge',damage=17,speed=430,active=5),M('Night Bloom','Nova',damage=17,wound=45)],hp=110,speed=177,reach=2100,axes=(2,4,4,1,1,4,1,4))
S('Bellox','three-hit resonator','Resonance','A bell-backed ox whose third direct hit rings louder.','Land two reliable taps, line up a decisive third contact.','Break its contact rhythm and force the third hit into a guard.','Track a persistent hit counter through movement and cooldown choices.',[
 M('Clapper',damage=14,cooldown=21),M('Bell Wave','Beam',damage=18,range=8500,radius=420),M('Peal Rush','Lunge',damage=16,impulse=400),M('Resonant Shell','Ward',shield=23,guard=24)],hp=133,speed=142,mass=130,reach=2800,axes=(3,3,2,2,1,1,3,4))
S('Anvilnewt','shield-to-offense converter','Forge','A newt that forges stronger blows while shielded.','Prepare a shield, enter while it lasts, choose whether to risk losing the damage buff.','Poke away the shield before the real exchange; use anti-shield tools.','Treat shield as both survival and an expiring offensive resource.',[
 M('Hammer Tongue',damage=19,startup=9),M('Forged Bolt','Bolt',damage=17,range=8500),M('Temper','Ward',shield=32,guard=0,cooldown=105),M('Anvil Fall','Nova',damage=24,slow=24,startup=18)],hp=130,speed=139,mass=125,reach=2300,axes=(2,4,1,2,1,1,4,3))
S('Duneskink','travel-charged skirmisher','Skirmish','A skink that stores actual distance traveled for the next strike.','Circle to build momentum, spend it in a short trade, move again.','Pin it or force it to fight before it has moved enough.','Plan paths with tactical purpose rather than running in place for charge.',[
 M('Sandlash',damage=16),M('Dune Dart','Bolt',damage=12,range=9000),M('Sand Sprint','Lunge',damage=14,speed=470,active=6),M('Dust Kick','Nova',damage=12,slow=40,impulse=350)],hp=108,speed=190,reach=3500,axes=(3,3,5,2,1,1,1,4))
S('Kelpwidow','ranged tether controller','Tether','A long-limbed widow that keeps prey at a precise intermediate range.','Tag from distance, pull toward a prepared patch, punish attempts to flee.','Commit fully through its preferred ring; do not oscillate on its strongest range.','Maintain a distance band under pressure rather than maximize distance.',[
 M('Kelp Harpoon','Bolt',damage=14,slow=30,range=10500,speed=390),M('Reel In','Beam',damage=14,impulse=-600,root=12,range=8500),M('Tangle Bed','Field',damage=3,root=9,period=30),M('Leg Sweep','Nova',damage=14,impulse=550)],hp=119,speed=143,reach=4700,axes=(4,3,2,5,4,1,1,5))
S('Pyrelisk','heat-risk siege mage','Overheat','A lizard that becomes stronger and slower as it casts.','Build heat safely, spend its amplified area damage before being surrounded.','Force mobility at high heat or wait while the heat drains.','Decide when another cast is worth losing movement speed.',[
 M('Heat Lance','Beam',damage=23,startup=20),M('Coal Fan','Bolt',damage=8,shots=3,spread=210,burn=45),M('Furnace','Field',damage=5,burn=30,radius=2100),M('Vent','Nova',damage=16,impulse=500,cleanse=1)],hp=122,speed=147,reach=5100,axes=(5,5,1,2,4,1,1,4))
S('Mooncalf','stored retaliation','Retaliate','A calf that stores shield damage for a later direct hit.','Offer a shielded trade, preserve the stored force, choose a reliable counterstrike.','Stop hitting the shield or force its next attack to miss.','Remember shield absorption and distinguish damage bait from a losing trade.',[
 M('Moon Tap',damage=15),M('Lunar Shield','Ward',shield=34,guard=18,cooldown=111),M('Moonbeam','Beam',damage=20,range=9500),M('Orbit','Lunge',damage=13,haste=30)],hp=130,speed=147,reach=3300,axes=(3,3,2,1,1,1,5,5))
S('Coppergecko','three-cast resource recycler','Recycle','A gecko whose every third cast refunds stamina.','Use a cheap tool to approach the refund, then spend on a high-cost spell.','Pressure it between refunds and deny low-risk filler casts.','Plan the cast counter and avoid wasting refunds at full energy.',[
 M('Copper Ping','Bolt',damage=11,cost=70,cooldown=24),M('Coil Cannon','Beam',damage=27,cost=260,cooldown=69),M('Springwire','Lunge',damage=15,cost=210),M('Capacitor','Ward',shield=20,guard=12,cost=130)],hp=114,speed=163,regen=4,reach=4100,axes=(4,3,3,1,1,1,2,5))
S('Orchardboar','delayed garden harvest','Harvest','A boar that receives a heal when its garden expires naturally.','Plant ahead of the fight, survive until harvest, then contest again.','Kill it before the payout; destroying turrets does not count as a harvest.','Track zone lifetimes and avoid taking a fight too early.',[
 M('Root Tusk',damage=20,impulse=300),M('Falling Fruit','Bolt',damage=16,speed=310),M('Orchard','Field',damage=3,lifetime=120,slow=15),M('Harvest Run','Lunge',damage=14,shield=12)],hp=139,speed=137,mass=140,reach=2800,axes=(3,3,2,2,4,4,3,3))
S('Inkheron','projectile cover architect','Cover','A heron whose own ink zones consume hostile projectiles.','Put ink between itself and a shooter, then exploit the safe firing angle.','Use beams, melee or walk around the cover; smoke is visible and not stealth.','Distinguish projectile cover from safety against all attack kinds.',[
 M('Ink Needle','Bolt',damage=15,range=11500),M('Ink Cloud','Field',damage=2,range=3800,radius=2200,lifetime=120),M('Brushstroke','Beam',damage=21,range=8500),M('Takeoff','Blink',range=3000)],hp=108,speed=161,reach=5900,axes=(5,3,3,1,4,1,3,4))
S('Hooklynx','marked catch specialist','Hunter','A lynx that wants to hook a marked target rather than any target.','Tag with a cheap dart, hook into claw range, cash out the mark.','Break line of sight after the tag and punish a missed hook recovery.','Wait for a high-value hook instead of firing it at maximum range every time.',[
 M('Trail Dart','Bolt',damage=10,mark=150,range=10000),M('Hookline','Beam',damage=15,impulse=-1100,range=9000,startup=20),M('Claim Claw',damage=20,bonus_mark=12),M('Hunting Bound','Lunge',damage=13,haste=30)],hp=119,speed=167,reach=2600,axes=(4,5,3,4,1,1,1,5))
S('Slagjaw','anti-sustain bruiser','Corrode','A corrosive jaw that makes all contact compromise healing.','Keep wounds on the opponent and take extended trades their heals cannot erase.','Take short burst trades and deny repeated contact rather than relying on recovery.','Identify sustain windows and keep access without overchasing.',[
 M('Corrosive Bite',damage=19,wound=90),M('Acid Spit','Bolt',damage=14,poison=60,range=9500),M('Slag Trail','Field',damage=4,wound=60),M('Jawbreaker','Lunge',damage=19,impulse=300)],hp=135,speed=147,mass=125,reach=2600,axes=(3,4,2,1,3,1,3,3))
S('Dewotter','reactive evasive cleanser','Purify','An otter whose dodge removes slows and damage-over-time effects.','Invite a debuff, cleanse through dodge, return while the enemy setup is down.','Bait dodge before applying the important debuff; use silence carefully.','Value cleanse timing while still respecting dodge stamina.',[
 M('Dew Dart','Bolt',damage=15,speed=470),M('River Cut',damage=18,slow=20),M('Waterwheel','Nova',damage=17,impulse=350),M('Fresh Spring','Ward',shield=12,heal=10,cleanse=1,cooldown=180)],hp=111,speed=178,reach=4000,axes=(3,2,4,2,1,3,3,4))
S('Echofin','timed cast cadence','Rhythm','A sonar fish paid for casting within a particular rhythm.','Space casts at roughly one-second intervals, then line up a broad payoff.','Interrupt its timing by forcing defense or denying range on the beat.','Learn temporal rhythm rather than pure cooldown greed.',[
 M('Sonar Tap','Beam',damage=15,startup=9,recovery=8,cooldown=27,range=8000),M('Echo Fan','Bolt',damage=8,shots=3,spread=240),M('Bass Ring','Nova',damage=24,min_range=1200,radius=3400),M('Silent Beat','Ward',shield=17,guard=12,haste=30)],hp=116,speed=156,reach=4000,axes=(4,4,3,1,1,1,2,5))
S('Latchspider','web-network mover','Web','A spider whose own zones accelerate it.','Lay a route of webs, fight while moving along it, pull enemies across it.','Force it out of the network or contest before it has placed safe routes.','Use terrain as a locomotion network rather than a stationary damage patch.',[
 M('Silk Dart','Bolt',damage=12,slow=30),M('Webway','Field',damage=2,slow=30,radius=2000,lifetime=180,cooldown=90),M('Latch','Beam',damage=14,impulse=-650,range=7500),M('Skitter','Lunge',damage=13,speed=400,active=5)],hp=110,speed=162,reach=3600,axes=(3,3,4,4,5,1,1,5))
S('Flintroc','charged first-strike artillery','Magazine','A roc that charges a powerful shot by not attacking.','Hold fire to charge, select a good lane, then reposition while reloading.','Pressure during its reload and force it to spend charge on a poor shot.','Trade shot frequency for reliability and avoid dumping charge into a dodge.',[
 M('Flint Cannon','Bolt',damage=22,startup=18,recovery=17,cooldown=66,speed=580,range=15500,radius=160,min_range=2500),M('Stone Scatter','Bolt',damage=7,shots=4,spread=180,range=8000),M('Backdraft','Nova',damage=13,impulse=650),M('Ridge Hop','Blink',range=2500,cooldown=165)],hp=105,speed=145,reach=8000,axes=(5,5,2,1,1,1,1,5))
S('Oathhound','guard-and-riposte sentinel','Resolve','A hound that resists interruption during guard and rewards a successful block.','Present a guarded threat, absorb contact, answer with an empowered strike.','Feint the guard and use displacement or long-range pressure instead of feeding it.','Read commitment and distinguish an incoming hit from a harmless telegraph.',[
 M('Oath Fang',damage=18),M('Sworn Guard','Ward',shield=23,guard=27,cooldown=96),M('Intercept','Lunge',damage=18,shield=10,impulse=250),M('Judgment','Beam',damage=21,range=7500,slow=24)],hp=139,speed=143,mass=140,reach=2600,axes=(3,3,2,2,1,1,5,4))
assert len(rows)==40 and len({s['name'] for s in rows})==40
out={'rules_version':2,'observation_version':2,'axes':['reach','commitment','mobility','control','persistence','sustain','defense','execution'],'species':rows,'dodge':M('Dodge','Evade',startup=1,active=6,recovery=8,cooldown=36,cost=240,damage=0,range=0,radius=0,speed=410)}
(ROOT/'content/roster.json').write_text(json.dumps(out,indent=2)+'\n')
print('Authored 40 species / 160 signature moves + shared dodge')
