#!/usr/bin/env python3
"""Validate and compile authored campaign data without runtime JSON dependencies."""
import json,sys
from campaign_geography import tiles
from pathlib import Path
root=Path(__file__).resolve().parents[1]
data=json.loads((root/'content/campaign.json').read_text())
regions=data['regions'];assert len(regions)==8
seen=[];lines=['// Generated by scripts/compile_campaign.py. Edit content/campaign.json.','#include "creature/campaign.hpp"','namespace creature::campaign {','const std::array<Region,RegionCount> Regions{{']
kinds=['Sanctuary','Conversation','Wild','Trial','Cache','Puzzle','Keeper','Gate','Expedition','Memory']
for r in regions:
 assert len(r['sites'])==20 and len(r['species'])==5
 seen+=r['species'];assert 0<=r['arena']<6 and 0<=r['weather']<3
 vals=[json.dumps(r[k],ensure_ascii=True) for k in ['name','subtitle','theme','arrival','epilogue']]
 vals += [str(r['arena']),str(r['weather']),'{'+','.join(map(str,r['species']))+'}']
 lines.append('{'+','.join(vals)+',{{')
 for i,s in enumerate(r['sites']):
  assert s['kind'] in kinds and 0<=s['species']<40 and -1<=s['prerequisite']<20 and s['prerequisite']!=i
  assert 1<s['x']<62 and 1<s['y']<46
  assert all(s[k] for k in ['name','speaker','text','after'])
  visited={i};at=s['prerequisite']
  while at>=0:assert at not in visited;visited.add(at);at=r['sites'][at]['prerequisite']
  lines.append('{'+','.join([json.dumps(s['name']),str(s['x']),str(s['y']),s['kind'],str(s['species']),str(s['prerequisite'])]+[json.dumps(s[k]) for k in ['speaker','text','after']])+'},')
 lines.append('}}},')
assert sorted(seen)==list(range(40))
lines+=['}};','const std::array<std::array<uint8_t, MapWidth * MapHeight>, RegionCount> Maps{{']
for number,region in enumerate(regions):
 lines.append('{{')
 for row in tiles(region,number):lines.append(','.join(map(str,row))+',')
 lines.append('}},')
lines+=['}};','}'];result='\n'.join(lines)+'\n';out=root/'src/campaign_content.cpp'
if '--check' in sys.argv:assert out.read_text()==result,'Stale campaign content'
else:out.write_text(result)
print('Validated 8 regions, 160 sites, 40 obtainable species, acyclic quest prerequisites.')
