#!/usr/bin/env python3
"""Validate canonical JSON, emit native immutable tables and readable species cards."""
import json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'scripts'))
# Do not import author_roster: imports must never overwrite designer edits.
KINDS=['Melee','Bolt','Lunge','Field','Evade','Beam','Nova','Trap','Ward','Blink','Turret']
PASSIVES=['Cinder','Anchor','Focus','Conduit','Venom','Bulwark','Frost','Backstab','Mirror','Rainborn','Trapper','Renewal','Ambush','Ricochet','Wounder','Sanctuary','Tailwind','Berserk','Cadence','Nullify','Architect','Returner','Reservoir','Leech','Resonance','Forge','Skirmish','Tether','Overheat','Retaliate','Recycle','Harvest','Cover','Hunter','Corrode','Purify','Rhythm','Web','Magazine','Resolve']
FIELDS='startup active recovery cooldown cost damage range radius speed impulse burn haste pierces_evasion min_range lifetime period shots spread slow root silence poison wound mark shield heal guard cleanse drain bonus_mark execute health_cost bounces returning pierce move_start move_active move_recovery surface surface_radius surface_life element wind_strength wind_duration'.split()
raw=(ROOT/'content/roster.json').read_bytes();data=json.loads(raw);species=data['species'];assert len(species)==40
moves=[]
for i,s in enumerate(species):
 assert s['id']==i and s['passive']==PASSIVES[i] and len(s['moves'])==4
 assert 80<=s['hp']<=180 and 100<=s['speed']<=210 and 250<=s['radius']<=700 and 2<=s['regen']<=12 and 70<=s['mass']<=200
 assert 1<=s['turn_degrees']<=20 and all(1<=s[k]<=100 for k in ['strafe','backward'])
 assert all(1<=s[k]<=6 for k in ['acceleration','braking']) and 50<=s['dodge_speed']<=150
 assert 50<=s['wind_affinity']<=300
 assert len(s['axes'])==8 and all(1<=a<=5 for a in s['axes'])
 assert all(s[k] for k in ['identity','loop','counterplay','learning_test'])
 moves.extend(s['moves'])
moves.append(data['dodge'])
assert len({m['name'] for m in moves})==len(moves)
for m in moves:
 assert m['kind'] in KINDS and set(m)==set(FIELDS+['name','kind']),m['name']
 assert all(type(m[f]) is int for f in FIELDS)
 assert 1<=m['startup']<=60 and 1<=m['active']<=30 and 1<=m['recovery']<=60
 assert m['cooldown']>=m['startup']+m['active']+m['recovery'] and m['cooldown']<=600,m['name']
 assert 0<=m['cost']<=600 and 0<=m['damage']<=60 and 0<=m['range']<=20*1024
 assert 0<=m['min_range']<=max(m['range'],m['radius']) and 0<=m['radius']<=4*1024
 assert 0<=m['speed']<=800 and 1<=m['shots']<=4 and 0<=m['spread']<=400
 assert all(0<=m[k]<=600 for k in ['burn','haste','lifetime','slow','root','silence','poison','wound','mark','guard'])
 assert all(0<=m[k]<=100 for k in ['move_start','move_active','move_recovery'])
 assert 0<=m['surface']<=6 and 0<=m['element']<=4
 assert 0<=m['surface_radius']<=4*1024 and 0<=m['surface_life']<=600
 assert 0<=m['wind_strength']<=24 and 0<=m['wind_duration']<=600
 assert (m['surface']==0)==(m['surface_life']==0) and (m['wind_strength']==0)==(m['wind_duration']==0)
 assert 1<=m['period']<=90 and 0<=m['bounces']<=3 and abs(m['impulse'])<=1600
 assert all(m[k] in [0,1] for k in ['pierces_evasion','cleanse','returning','pierce'])
h=2166136261
for b in raw:h=((h^b)*16777619)&0xffffffff
lines=['// Generated by scripts/compile_content.py; edit content/roster.json.','#include "creature/sim.hpp"','namespace creature {',f'const uint32_t ContentHash = {h}u;','const std::array<Move,MoveCount> Moves{{']
for m in moves:lines.append('{'+json.dumps(m['name'])+','+m['kind']+','+','.join(str(m[k]) for k in FIELDS)+'},')
lines+=['}};','const std::array<Species,SpeciesCount> Roster{{']
for s in species:
 lines.append('{'+','.join(json.dumps(s[k]) for k in ['name','role','identity'])+','+','.join(str(s[k]) for k in ['hp','speed','radius','regen','mass'])+','+s['passive']+','+str(s['preferred_range'])+',{'+','.join(str(s['id']*4+j) for j in range(4))+'},{'+','.join(map(str,s['axes']))+'},'+','.join(str(s[k]) for k in ['turn_degrees','strafe','backward','acceleration','braking','dodge_speed','wind_affinity'])+'},')
lines+=['}};','}']
cpp='\n'.join(lines)+'\n'
if '--check' in sys.argv:
 assert (ROOT/'src/content.cpp').read_text()==cpp,'Generated content is stale'
else:(ROOT/'src/content.cpp').write_text(cpp)
doc=['# Alpha species field guide','', 'All 40 species and 160 signature moves below are executable content. Shared dodge is slot 5. Times are simulation ticks at 30 Hz; range/radius are game units. Axis scores are design intent, not measured power.','', '| # | Species | Role | Passive | HP | Speed (units/s) |', '|---|---|---|---|---:|---:|']
for s in species:doc.append(f"| {s['id']+1} | [{s['name']}](#{s['name'].lower()}) | {s['role']} | {s['passive']} | {s['hp']} | {s['speed']*30/1024:.2f} |")
for s in species:
 doc+=['',f"## {s['name']}",'',s['identity'],'',f"**Body:** {s['hp']} HP; {s['speed']*30/1024:.2f} units/s; {s['radius']/1024:.2f} collider radius; mass {s['mass']}; stamina regeneration {s['regen']*30}/s.",'',f"**Locomotion:** turns {s['turn_degrees']*30} degrees/s; strafe {s['strafe']}%; reverse {s['backward']}%; acceleration divisor {s['acceleration']}; braking divisor {s['braking']}; dodge speed {s['dodge_speed']}%; wind affinity {s['wind_affinity']}%.",'',f"**Winning pattern:** {s['loop']}",'',f"**Counterplay:** {s['counterplay']}",'',f"**Learning test:** {s['learning_test']}",'', '**Axes (1–5):** '+', '.join(f'{a} {v}' for a,v in zip(data['axes'],s['axes']))+'.','', '| Slot / move | Form | Damage | Startup / active / recovery | CD / stamina | Range / radius | Effects |','|---|---|---:|---|---|---|---|']
 for j,m in enumerate(s['moves']):
  effects=', '.join(f'{f}={m[f]}' for f in FIELDS if f not in ['startup','active','recovery','cooldown','cost','damage','range','radius','period','shots','spread'] and m[f]) or 'none'
  if m['shots']>1:effects+=f", shots={m['shots']}"
  if m['lifetime']:effects+=f", pulse every {m['period']}t"
  doc.append(f"| {j+1}. {m['name']} | {m['kind']} | {m['damage']} | {m['startup']} / {m['active']} / {m['recovery']} | {m['cooldown']}t / {m['cost']} | {m['range']/1024:.2f} / {m['radius']/1024:.2f} | {effects} |")
if '--check' not in sys.argv:(ROOT/'docs/alpha/species.md').write_text('\n'.join(doc)+'\n')
print(f'Validated {len(species)} species, {len(moves)} moves; content fingerprint {h:08x}')
